### PR TITLE
Update create_package.py

### PR DESCRIPTION
**Pull request by MustafaJafar**
## Changelog Description
Skip few paths if they don't exist. 

## Additional info
This PR is not necessary for this example addon as `client` directory, `pyproject.toml`  and `frontend` always exist.
But, this PR becomes handy when someone is using this addon as template where they may don't need  `pyproject.toml`  and `frontend`.

> [!NOTE]
> Please feel free to suggest closing this PR  if you think it doesn't add a value.
> However, I'm using the same `create_package.py` in this branch in multiple places (locally on my side when making some trials to learn about addon creation).

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
> This PR is not necessary for this example addon as pyproject.toml and frontend always exist.
But, this PR becomes handy when someone is using this addon as template where they may don't need pyproject.toml and frontend.

Shouldn't they modify the script in that case?

**Comment by MustafaJafar** [comment]
> Shouldn't they modify the script in that case?

Yes, I just wanted to simplify it for newcomers.

**Comment by iLLiCiTiT** [comment]
Then I would add some explanation comments. Now newcommers would have to read the code to understand...

**Comment by MustafaJafar** [comment]
> Then I would add some explanation comments. Now newcommers would have to read the code to understand...

@iLLiCiTiT, I've added more logs.

**Comment by iLLiCiTiT** [comment]
BTW have you tried create package from addon template repository?

https://github.com/ynput/ayon-addon-template/blob/develop/create_package.py

**Comment by MustafaJafar** [comment]
> BTW have you tried create package from addon template repository?
> 
> https://github.com/ynput/ayon-addon-template/blob/develop/create_package.py

Oh may, that's far better. Many thanks.
closing this PR. and I'll always refer to the https://github.com/ynput/ayon-addon-template/blob/develop/create_package.py in my future guides/docs.

**Pull request closed without merging**
